### ISSUE TITLE
prevent autoclosing if mouse cursor over minimap 

### ISSUE THREAD

**Issue by nobodo** [ansballard/minimap-autohider#9] opened 2017-09-06 07:04 UTC
Trying to click the cog wheel button was a bit frustrating when autohide kicked in just before mouse cursor was reaching the button.

**Comment by ansballard** [comment] 2017-09-07 15:04
weird, I can't reproduce that on my box (windows 10). What OS are you using, and is atom/this package up to date? Thanks for the issue!

**Comment by ansballard** [comment] 2017-11-06 16:12
Going to close this for my sanity, but if it isn't actually resolved just let me know!

**Closed as completed by ansballard** 2017-11-06 16:12 UTC
